name: Build Apk
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated from v2 to v4

    - name: Sign with debug key
      run: |
        sed -i "19i signingConfig signingConfigs.debug" ./app/build.gradle
        curl -so- https://raw.githubusercontent.com/artem-zinnatullin/RxJavaProGuardRules/master/rxjava-proguard-rules/proguard-rules.txt | tee -a ./app/proguard-rules.pro
        cat ./app/proguard-rules.pro

    - name: Set up JDK 11
      uses: actions/setup-java@v4  # Updated from v2 to v4
      with:
        java-version: '11'
        distribution: 'temurin'  # Changed from 'adopt' to 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Get App Version Name
      id: version
      run: |
        version=$(grep versionName app/build.gradle | sed -n 's/.*versionName \"\([0-9.]*\)\".*/\1/p')
        echo "app_version=$version" >> $GITHUB_OUTPUT  # Updated set-output method

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk game-unlocker-v${{ steps.version.outputs.app_version }}.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4  # Updated from v2 to v4
      with:
        name: Game Unlocker
        path: game-unlocker-v${{ steps.version.outputs.app_version }}.apk

    - name: Create Release
      id: create_release
      uses: actions/create-release@v2  # Updated from v1 to v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.app_version }}
        release_name: ${{ steps.version.outputs.app_version }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1  # Simpler alternative to curl
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: game-unlocker-v${{ steps.version.outputs.app_version }}.apk
        asset_name: game-unlocker-v${{ steps.version.outputs.app_version }}.apk
        asset_content_type: application/zip