name: Build Apk
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Sign with debug key
      run: |
        sed -i "19i signingConfig signingConfigs.debug" ./app/build.gradle
        curl -so- https://raw.githubusercontent.com/artem-zinnatullin/RxJavaProGuardRules/master/rxjava-proguard-rules/proguard-rules.txt | tee -a ./app/proguard-rules.pro
        cat ./app/proguard-rules.pro

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Get App Version Name
      id: version
      run: |
        version=$(grep versionName app/build.gradle | sed -n 's/.*versionName \"\([0-9.]*\)\".*/\1/p')
        echo "app_version=$version" >> $GITHUB_OUTPUT

    - name: Rename APK
      run: mv app/build/outputs/apk/debug/app-debug.apk game-unlocker-v${{ steps.version.outputs.app_version }}.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Game Unlocker
        path: game-unlocker-v${{ steps.version.outputs.app_version }}.apk

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: game-unlocker-v${{ steps.version.outputs.app_version }}.apk
        tag_name: ${{ steps.version.outputs.app_version }}
        name: ${{ steps.version.outputs.app_version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/zip" \
          "${{ steps.create_release.outputs.upload_url }}?name=game-unlocker-v${{ steps.version.outputs.app_version }}.apk" \
          --data-binary "@game-unlocker-v${{ steps.version.outputs.app_version }}.apk"
